spring:  
  profiles: 
    active: prod
  application:
    name: helper
  http:
    encoding:
      charset: UTF-8
    multipart:
      enabled: true 
      max-file-size: 5MB  #上传文件最大的大小，因此上传的图片不可超过这个大小，否则抛出异常
      max-request-size: 10MB 
#  jackson: 
#    default-property-inclusion: NON_EMPTY   
#config-location: classpath:mybatis-config.xml     
#mybatis:
#  mapper-locations: classpath*:mapper/**/*.xml
#  config-location: classpath:mybatis-config.xml   
# 


#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.wlgroup.*.domain;com.wlgroup.*.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false  
