server:  
  port: 8383

spring: 
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/pddzushou?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 
    driver_class_name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    
    max-active: 20
    initial-size: 1
    min-idle: 3
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    poolPreparedStatements: true
 

    
logging: 
  config: classpath:log4j2-dev.xml

#flyway:
#  validate-on-migrate: exfalse

helper:
  swagger-open: true #是否开启swagger (true/false)  

client:
  id: '56b36ebebdb8433b868a647b8e681e67'
  secret: 'cd8acb2c3635b58bd778bac7aa19b1692dc5a842'
  
  
#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.wlgroup.*.domain;com.wlgroup.*.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false  


  
  